### ISSUE TITLE
email subject

### ISSUE THREAD

**Issue by chemix** [eventigo/eventigo-web#14]
Akce na pristi tyden => Akce na pristi tyden (#57, 12.6. - 24.5) ?

**Comment by TomasVotruba** [comment]
Můžeš to trochu rozepsat, Honzo? Nevím jestli je to issue, návrh na změnu a co znamejí ty čísla.

**Comment by chemix** [comment]
mozna jeden obrazek za spoustu slov?
![image](https://cloud.githubusercontent.com/assets/42802/23821889/091f68ea-0640-11e7-91c2-961f03d4137e.png)

**Comment by TomasVotruba** [comment]
Lepší, ale stále mi chybí ten use case - **co je tvoje potřeba** (ne řešení)?
Jak s tím pracuješ v koši?

Já třeba koukám jen na akce na příští týden. Nezajímá mě, co bylo před měsícem.

**Comment by chemix** [comment]
Seslo se mi ted v inboxu dva emaily po sobe a prislo mi zajimave abych je mel nejak vizualne odlisene

**Comment by TomasVotruba** [comment]
Aha, to už si dokážu představit. Díky.

Napadá mě použít označení dny toho týdne: 

*1. Akce na týden 13-19. března*

nebo 

*2. Akce na příští týden 13-19. března*

Bylo by to ok?

**Dokážeš na to poslat PR?**

**Comment by filipsuk** [comment]
Můžu zkusit příští týden poslat v tomto formátu. Pokud by se dělalo PR, tak stačí úprava newsletter:create commandu. Volil bych kratší verzi 1.

**Comment by chemix** [comment]
To bude asi tady? https://github.com/eventigo/eventigo-web/blob/master/app/Modules/Newsletter/Model/NewsletterService.php#L85 ze?

**Comment by filipsuk** [comment]
@chemix presne tak. Asi se ztrati moznost menit defaultSubject v configu (pokud by se nevymyslel nejakej chytrej system placeholderu pro datum), ale to neni zadna tragedie. Moje workflow kazdy ctvrtek (zjednodusene)

1. create command
2. naplneni newsletteru html obsahem primo v db (tedy intro a outro.. sekce s akcemi na pristi tyden se renderuje pro kazdeho jinak)
3. preview pres dynamic action v newsletter presenteru
4. render command
5. send command
