### ISSUE TITLE
Links in emails without base url

### ISSUE THREAD

**Issue by filipsuk** [eventigo/eventigo-web#20]
Event links in last newsletter look like this:
```
http://redirect/?url=https%3A%2F%2Ffacebook.com%2Fevents%2F266045747192476%2F
```
It is not a SendGrid problem.

Dynamic newsletter preview e.g. `https://eventigo.cz/newsletter/dynamic/5` works OK. Looks like console command problem (`newsletters:render`).

**Edit:**
Link should look like this:
```
https://eventigo.cz/redirect/?url=https%3A%2F%2Ffacebook.com%2Fevents%2F1325356277554063%2F
```

**Comment by TomasVotruba** [comment]
How should they look like?

What is the responsible class?

**Comment by fprochazka** [comment]
Let me guess: it worked with [kdyby/console](https://github.com/Kdyby/Console), right? ;)

Nette doesn't have HttpRequest populated in CLI, so the links cannot be properly generated. `LinkGenerator` depends on HttpRequest.

You need this [contributte/http](https://github.com/contributte/http/blob/561128953c503e3472617878def0a2e2714de035/src/SAPI/DI/SapiRequestExtension.php) (or.. you know... Kdyby/Console)

**Comment by TomasVotruba** [comment]
I see :-) my bad.

Let me fix that and add test next week. I'm tripping over Vienna and BA now

**Comment by f3l1x** [comment]
Oh. :) We could add it to contributte/console, but as @fprochazka mentioned, it´s in contributte/http.

**Comment by f3l1x** [comment]
@TomasVotruba @filipsuk I've completly forgot that providing URL is already in `contributte/console`.

https://github.com/contributte/console/blob/master/.docs/README.md#configuration

**Comment by TomasVotruba** [comment]
@f3l1x Great to know. Could you send PR for that please?

**Comment by f3l1x** [comment]
Related: https://github.com/eventigo/eventigo-web/pull/21
